spring.application.name=bus-reservation-system

spring.datasource.url=jdbc:postgresql://localhost:5432/busreservationdb
spring.datasource.username=postgres
spring.datasource.password=godgamerian
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=6a233f5a62e7108cedfad11095a183baddb6299c958e559374cc3cb3db240663ad9c74a764fbf094c38e9e375f957091ac662ab7018bb4e76191122e5e161171
jwt.expiration-ms=172800000

frontend.url=http://localhost:5173

logging.level.org.springframework.security=DEBUG

# Show transaction boundaries
logging.level.org.springframework.transaction=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gauravswargiary0702@gmail.com
spring.mail.password=vyhk dwob cmxz nyly
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

